# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

Usman I Hassan <usmanhassanish@gmail.com>
Nqobile Mdlalose <mdlalose150@gmail.com>
